#define _POSIX_C_SOURCE 200809L

#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "linux_shortcut.h"

static int failures = 0;

#define CHECK(expression)                                                        \
    do {                                                                         \
        if (!(expression)) {                                                     \
            (void)fprintf(                                                       \
                stderr, "%s:%d: check failed: %s\n",                         \
                __FILE__, __LINE__, #expression);                                \
            failures += 1;                                                       \
        }                                                                        \
    } while (0)

static bool join_path(
    char *output,
    size_t output_capacity,
    const char *left,
    const char *right)
{
    int written = snprintf(output, output_capacity, "%s/%s", left, right);

    return written >= 0 && (size_t)written < output_capacity;
}

static bool write_text(const char *path, const char *text)
{
    FILE *file = fopen(path, "wb");
    size_t length = strlen(text);
    bool success = file != NULL && fwrite(text, 1U, length, file) == length;

    if (file != NULL && fclose(file) != 0) {
        success = false;
    }
    return success;
}

static void test_xdg_directory_and_shortcut_contract(void)
{
    char root_template[] = "/tmp/loim-shortcut-test.XXXXXX";
    char *root = root_template;
    int temporary_file = mkstemp(root_template);
    char config[PATH_MAX];
    char desktop[PATH_MAX];
    char settings[PATH_MAX];
    char entry[PATH_MAX];
    char other_entry[PATH_MAX];
    char shortcut[PATH_MAX];
    char resolved[PATH_MAX];
    char copied[128];
    FILE *copied_file;
    struct stat metadata;

    CHECK(temporary_file >= 0);
    if (temporary_file < 0) {
        return;
    }
    CHECK(close(temporary_file) == 0);
    CHECK(unlink(root) == 0);
    CHECK(mkdir(root, 0700) == 0);
    CHECK(join_path(config, sizeof(config), root, ".config"));
    CHECK(join_path(desktop, sizeof(desktop), root, "桌面"));
    CHECK(join_path(settings, sizeof(settings), config, "user-dirs.dirs"));
    CHECK(join_path(entry, sizeof(entry), root, "com.ctdy123.loimreader.desktop"));
    CHECK(join_path(other_entry, sizeof(other_entry), root, "other.desktop"));
    CHECK(join_path(shortcut, sizeof(shortcut), desktop, "LoimReader.desktop"));
    CHECK(mkdir(config, 0700) == 0);
    CHECK(mkdir(desktop, 0700) == 0);
    CHECK(write_text(
        settings,
        "# generated by xdg-user-dirs-update\n"
        "XDG_DESKTOP_DIR=\"$HOME/桌面\"\n"));
    CHECK(write_text(
        entry,
        "[Desktop Entry]\nType=Application\nX-LoimReader-Managed=true\n"));

    CHECK(loim_linux_resolve_desktop_directory(
        root, config, resolved, sizeof(resolved)));
    CHECK(strcmp(resolved, desktop) == 0);
    CHECK(loim_linux_desktop_shortcut_ensure(
              resolved, entry, "LoimReader.desktop") ==
          LOIM_SHORTCUT_CREATED);
    CHECK(lstat(shortcut, &metadata) == 0);
    CHECK(S_ISREG(metadata.st_mode));
    CHECK((metadata.st_mode & 0111) == 0111);
    copied_file = fopen(shortcut, "rb");
    CHECK(copied_file != NULL);
    if (copied_file != NULL) {
        CHECK(fgets(copied, (int)sizeof(copied), copied_file) != NULL);
        CHECK(strcmp(copied, "[Desktop Entry]\n") == 0);
        CHECK(fclose(copied_file) == 0);
    }
    CHECK(loim_linux_desktop_shortcut_ensure(
              resolved, entry, "LoimReader.desktop") ==
          LOIM_SHORTCUT_ALREADY_PRESENT);
    CHECK(chmod(shortcut, 0644) == 0);
    CHECK(loim_linux_desktop_shortcut_ensure(
              resolved, entry, "LoimReader.desktop") ==
          LOIM_SHORTCUT_CREATED);
    CHECK(stat(shortcut, &metadata) == 0);
    CHECK((metadata.st_mode & 0111) == 0111);

    CHECK(unlink(shortcut) == 0);
    CHECK(symlink(entry, shortcut) == 0);
    CHECK(loim_linux_desktop_shortcut_ensure(
              resolved, entry, "LoimReader.desktop") ==
          LOIM_SHORTCUT_CREATED);
    CHECK(lstat(shortcut, &metadata) == 0);
    CHECK(S_ISREG(metadata.st_mode));
    CHECK((metadata.st_mode & 0111) == 0111);

    CHECK(unlink(shortcut) == 0);
    CHECK(write_text(shortcut, "user-owned file\n"));
    CHECK(loim_linux_desktop_shortcut_ensure(
              resolved, entry, "LoimReader.desktop") ==
          LOIM_SHORTCUT_CONFLICT);
    CHECK(access(shortcut, F_OK) == 0);

    CHECK(unlink(shortcut) == 0);
    CHECK(write_text(other_entry, "[Desktop Entry]\nType=Application\n"));
    CHECK(symlink(other_entry, shortcut) == 0);
    CHECK(loim_linux_desktop_shortcut_ensure(
              resolved, entry, "LoimReader.desktop") ==
          LOIM_SHORTCUT_CONFLICT);
    CHECK(lstat(shortcut, &metadata) == 0);
    CHECK(S_ISLNK(metadata.st_mode));

    CHECK(unlink(shortcut) == 0);
    CHECK(unlink(other_entry) == 0);
    CHECK(unlink(entry) == 0);
    CHECK(unlink(settings) == 0);
    CHECK(rmdir(desktop) == 0);
    CHECK(rmdir(config) == 0);
    CHECK(rmdir(root) == 0);
}

static void test_safe_fallbacks(void)
{
    char path[PATH_MAX];

    CHECK(loim_linux_resolve_desktop_directory(
        "/home/example", "/missing/config", path, sizeof(path)));
    CHECK(strcmp(path, "/home/example/Desktop") == 0);
    CHECK(!loim_linux_resolve_desktop_directory(
        NULL, "/missing/config", path, sizeof(path)));
    CHECK(loim_linux_desktop_shortcut_ensure(
              "/missing/desktop",
              "/usr/share/applications/com.ctdy123.loimreader.desktop",
              "LoimReader.desktop") == LOIM_SHORTCUT_UNAVAILABLE);
}

int main(void)
{
    test_xdg_directory_and_shortcut_contract();
    test_safe_fallbacks();
    if (failures != 0) {
        (void)fprintf(stderr, "%d Linux shortcut check(s) failed\n", failures);
        return EXIT_FAILURE;
    }
    (void)puts("all Linux shortcut tests passed");
    return EXIT_SUCCESS;
}
