#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
project_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
source_svg=$project_dir/icons/loimreader.svg
linux_dir=$project_dir/icons/linux
work_dir=$(mktemp -d "${TMPDIR:-/tmp}/loimreader-icons.XXXXXX")

cleanup()
{
    rm -rf "$work_dir"
}
trap cleanup EXIT HUP INT TERM

if command -v magick >/dev/null 2>&1; then
    image_tool=magick
elif command -v convert >/dev/null 2>&1; then
    image_tool=convert
else
    echo "ImageMagick (magick or convert) is required" >&2
    exit 1
fi

render_png()
{
    size=$1
    output=$2
    mkdir -p "$(dirname -- "$output")"
    "$image_tool" -background none -density 384 "$source_svg" \
        -resize "${size}x${size}" -strip "PNG32:$output"
}

for size in 16 24 32 48 64 128 256 512; do
    render_png "$size" "$linux_dir/${size}x${size}/loimreader.png"
done
cp "$linux_dir/256x256/loimreader.png" "$project_dir/icons/loimreader.png"

iconset=$work_dir/LoimReader.iconset
mkdir -p "$iconset"
render_png 16 "$iconset/icon_16x16.png"
render_png 32 "$iconset/icon_16x16@2x.png"
render_png 32 "$iconset/icon_32x32.png"
render_png 64 "$iconset/icon_32x32@2x.png"
render_png 128 "$iconset/icon_128x128.png"
render_png 256 "$iconset/icon_128x128@2x.png"
render_png 256 "$iconset/icon_256x256.png"
render_png 512 "$iconset/icon_256x256@2x.png"
render_png 512 "$iconset/icon_512x512.png"
render_png 1024 "$iconset/icon_512x512@2x.png"

if command -v iconutil >/dev/null 2>&1; then
    iconutil -c icns "$iconset" -o "$project_dir/icons/macos.icns"
else
    echo "iconutil is required to regenerate icons/macos.icns" >&2
    exit 1
fi

ico_inputs=''
for size in 16 24 32 48 64 128 256; do
    render_png "$size" "$work_dir/windows-${size}.png"
    ico_inputs="$ico_inputs $work_dir/windows-${size}.png"
done
# The paths above are generated by this script and contain no shell metacharacters.
# shellcheck disable=SC2086
"$image_tool" $ico_inputs "$project_dir/icons/windows.ico"

echo "Generated LoimReader ICNS, ICO, and Linux PNG icon sets."
